name: Build

on: [push, pull_request]

env:
  # Supabase Configuration
  PUBLIC_SUPABASE_URL: "https://fake-test-url.supabase.co"
  PUBLIC_SUPABASE_ANON_KEY: "fake_anon_key"
  PRIVATE_SUPABASE_SERVICE_ROLE: "fake_service_role"

  # Google Configuration
  PUBLIC_GOOGLE_CLIENT_ID: "fake_google_client_id"
  GOOGLE_CLIENT_SECRET: "fake_google_secret"
  GOOGLE_CLOUD_PROJECT: "fake_project"
  GOOGLE_CLOUD_LOCATION: "us-central1"

  # Optional Services
  PRIVATE_STRIPE_API_KEY: "fake_stripe_api_key"
  PRIVATE_RESEND_API_KEY: "fake_resend_api_key"
  PRIVATE_ADMIN_EMAIL: "admin@example.com"
  CRON_SECRET: "fake_cron_secret"

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: NPM install
        run: npm ci

      - name: SvelteKit Build
        run: npm run build
