name: Continuous Integration

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run format check
        run: npm run format_check

      - name: Run type checking
        run: npm run check

      - name: Run tests
        run: npm run test_run

  database-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start local Supabase
        run: supabase db start

      - name: Validate migrations
        run: supabase db reset

      - name: Generate types
        run: supabase gen types typescript --local > src/DatabaseDefinitions.ts

      - name: Verify types are up to date
        run: |
          if ! git diff --exit-code src/DatabaseDefinitions.ts; then
            echo "Database types are not up to date. Please regenerate them."
            exit 1
          fi

  build-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          # Static fallback values for CI build
          PUBLIC_SUPABASE_URL: "https://fake-test-url.supabase.co"
          PUBLIC_SUPABASE_ANON_KEY: "fake_anon_key"
          PRIVATE_SUPABASE_SERVICE_ROLE: "fake_service_role"
          GOOGLE_CLOUD_PROJECT: "fake_project"
          GOOGLE_CLOUD_LOCATION: "us-central1"
          PUBLIC_GOOGLE_CLIENT_ID: "fake_google_client_id"
          GOOGLE_CLIENT_SECRET: "fake_google_secret"
          PRIVATE_STRIPE_API_KEY: "fake_stripe_api_key"
          PRIVATE_RESEND_API_KEY: "fake_resend_api_key"
          PRIVATE_ADMIN_EMAIL: "admin@example.com"
          CRON_SECRET: "fake_cron_secret"
